"""GitHub Discovery - Main entry point.

Discovers trending GitHub repos before they go mainstream.
Outputs top repos as markdown to stdout and file.
"""

import os
import sys
from datetime import datetime

# Ensure we can import sibling modules
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from config import TOP_N, OUTPUT_DIR
from db import init_db, repo_exists, save_repo, save_run
from sources import fetch_all
from scorer import calculate_score


def format_repo_markdown(repo: dict, scores: dict, rank: int) -> str:
    """Format a single repo as markdown."""
    name = repo["full_name"]
    url = repo["url"]
    stars = repo.get("stars", 0)
    age = repo.get("age_days", 1)
    daily = repo.get("daily_stars", 0)
    desc = repo.get("description", "No description")
    lang = repo.get("language", "Unknown")
    source = repo.get("source", "unknown")
    total = scores["total"]

    # Score bar
    bar_len = int(total / 5)
    bar = "█" * bar_len + "░" * (20 - bar_len)

    lines = [
        f"### {rank}. [{name}]({url})",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| ⭐ Stars | {stars:,} |",
        f"| 📅 Age | {age} days |",
        f"| 🚀 Daily Growth | {daily:.1f} stars/day |",
        f"| 🔤 Language | {lang} |",
        f"| 📡 Source | {source} |",
        f"",
        f"> {desc}",
        f"",
        f"**Score: {total}/100** `{bar}`",
        f"- Acceleration: {scores['acceleration']}/40",
        f"- Quality: {scores['quality']}/30",
        f"- Anti-spam: {scores['antispam']}/30",
        f"",
        f"---",
        f"",
    ]

    # HN bonus info
    if repo.get("hn_title"):
        lines.insert(-2, f"- 🔶 HN: [{repo['hn_title']}](https://news.ycombinator.com) (score: {repo.get('hn_score', 0)})")
        lines.insert(-2, "")

    return "\n".join(lines)


def generate_markdown(top_repos: list[tuple[dict, dict]]) -> str:
    """Generate full markdown report."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    header = f"""# 🔥 GitHub Discovery Report

> **Generated:** {now}
> **Top {len(top_repos)} repos** that are gaining traction before going mainstream

---

"""
    body = ""
    for i, (repo, scores) in enumerate(top_repos, 1):
        body += format_repo_markdown(repo, scores, i)

    summary = f"""
## 📊 Summary

- **Total repos analyzed:** {len(top_repos)} candidates scored
- **Score range:** {top_repos[-1][1]['total']} - {top_repos[0][1]['total']}
- **Top pick:** [{top_repos[0][0]['full_name']}]({top_repos[0][0]['url']})

---
*Generated by GitHub Discovery Tool*
"""
    return header + body + summary


def main():
    print("=" * 60)
    print("  GitHub Discovery Tool")
    print("  Finding repos before they go viral")
    print("=" * 60)
    print()

    # Init database
    init_db()

    # Fetch from all sources
    all_repos = fetch_all()

    if not all_repos:
        print("[ERROR] No repos found from any source. Check network/API.")
        sys.exit(1)

    # Score and filter
    scored = []
    for repo in all_repos:
        scores = calculate_score(repo)
        # Skip repos we've already recommended
        if repo_exists(repo["id"]):
            print(f"  [SKIP] {repo['full_name']} (already recommended)")
            continue
        scored.append((repo, scores))

    # Sort by total score descending
    scored.sort(key=lambda x: x[1]["total"], reverse=True)

    # Take top N
    top = scored[:TOP_N]

    if not top:
        print("[WARN] No new repos to recommend.")
        sys.exit(0)

    # Save to database
    for repo, scores in top:
        save_repo(repo, scores["total"], repo.get("source", "unknown"))
    save_run(len(scored), top[0][1]["total"])

    # Generate and output markdown
    md = generate_markdown(top)
    print(md)

    # Save to file
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    date_str = datetime.now().strftime("%Y-%m-%d")
    out_path = os.path.join(OUTPUT_DIR, f"discovery-{date_str}.md")
    with open(out_path, "w") as f:
        f.write(md)
    print(f"\n[Saved] Report written to {out_path}")

    # Print compact summary
    print("\n" + "=" * 60)
    print("  TOP PICKS SUMMARY")
    print("=" * 60)
    for i, (repo, scores) in enumerate(top[:5], 1):
        print(f"  {i}. {repo['full_name']:40s} ⭐{repo['stars']:>6,}  📊{scores['total']:>3}/100")
    if len(top) > 5:
        print(f"  ... and {len(top) - 5} more")


if __name__ == "__main__":
    main()
